import { escapeCsvValue } from '@/lib/compliance-export/csv';
import type { EconomicsExportData } from './data';

export type EconomicsCsvType='field_economics'|'crop_economics'|'purchases'|'expenses'|'harvest'|'revenue'|'budget_vs_actual'|'unallocated_records';
const bom=String.fromCharCode(0xfeff);
const csv=(headers:string[],rows:Array<Array<string|number|null|undefined>>)=>bom+[headers,...rows].map(row=>row.map(escapeCsvValue).join(',')).join('\r\n')+'\r\n';
const n=(value:unknown)=>value==null?'':String(Number(value));const d=(value:Date)=>value.toISOString().slice(0,10);

export function buildEconomicsCsv(type:EconomicsCsvType,data:EconomicsExportData,includeHistory=false){
  const {finance}=data;
  if(type==='field_economics')return csv(['field_id','field','crop','hectares','recorded_cost_eur','recorded_revenue_eur','gross_margin_eur','cost_per_ha_eur','yield_quantity','yield_unit','cost_per_yield_unit_eur','break_even_price_eur','completeness_pct','missing_categories'],finance.fields.map(row=>[row.fieldId,row.field,row.crop,n(row.hectares),n(row.recordedCostEur),n(row.recordedRevenueEur),n(row.grossMarginEur),n(row.costPerHaEur),n(row.yieldQuantity),row.yieldUnit,n(row.costPerYieldUnit),n(row.breakEvenPrice),row.completenessPercent,row.completenessResult.reasons.map(reason=>reason.code).join('; ')]));
  if(type==='crop_economics')return csv(['crop','field_count','hectares','recorded_cost_eur','recorded_revenue_eur','gross_margin_eur','cost_per_ha_eur','gross_margin_per_ha_eur','completeness_pct'],finance.crops.map(row=>[row.crop,row.fields,n(row.hectares),n(row.costEur),n(row.revenueEur),n(row.grossMarginEur),n(row.costPerHaEur),n(row.grossMarginPerHaEur),row.completenessPercent]));
  if(type==='purchases')return csv(['purchase_id','date','inventory_item','supplier','quantity','unit','unit_cost_eur','total_ex_vat_eur','vat_eur','invoice_reference','status'],data.purchases.filter(row=>includeHistory||row.status==='active').map(row=>[row.id,d(row.purchaseDate),row.inventoryItem.name,row.supplier,n(row.quantity),row.unit,n(row.unitCost),n(row.totalAmount),n(row.vatAmount),row.invoiceReference,row.status]));
  if(type==='expenses')return csv(['expense_id','date','field','source_type','description','quantity','unit','amount_eur','allocation_method','reference','status'],data.expenses.filter(row=>includeHistory||row.status==='active').map(row=>[row.id,d(row.expenseDate),row.fieldSeason?.field.name,row.sourceType,row.description,n(row.quantity),row.unit,n(row.amount),row.allocationMethod,row.reference,row.status]));
  if(type==='harvest')return csv(['harvest_id','date','field','harvested_area_ha','gross_quantity','saleable_quantity','unit','moisture_pct','quality_grade','batch_lot','status'],data.harvest.filter(row=>includeHistory||row.status==='active').map(row=>[row.id,d(row.harvestDate),row.fieldSeason.field.name,n(row.harvestedAreaHa),n(row.grossQuantity),n(row.saleableQuantity),row.unit,n(row.moisturePercent),row.qualityGrade,row.batchLot,row.status]));
  if(type==='revenue')return csv(['revenue_id','date','field','type','name','quantity','unit','price_per_unit_eur','total_eur','revenue_status','allocation_method','reference','record_status'],data.revenue.filter(row=>includeHistory||row.status==='active').map(row=>[row.id,d(row.revenueDate),row.fieldSeason?.field.name,row.type,row.name,n(row.quantity),row.unit,n(row.pricePerUnit),n(row.totalAmount),row.revenueStatus,row.allocationMethod,row.reference,row.status]));
  // Part 14 — unallocated records (expenses/revenue/subsidy/overhead/contractor
  // with a remaining unallocated amount). Directly-linked activity costs are
  // already excluded by getAllocatableRecords.
  if(type==='unallocated_records')return csv(['economic_entry_id','date','label','kind','source_type','amount_eur','allocated_eur','remaining_unallocated_eur','allocation_status','reference'],data.allocatable.filter(row=>row.unallocatedAmount>0.005).map(row=>[row.economicEntryId,row.date,row.label,row.kind,row.sourceType,n(row.amount),n(row.allocatedAmount),n(row.unallocatedAmount),row.status,row.reference]));
  return csv(['field_id','field','crop','budget_cost_eur','actual_cost_eur','cost_variance_eur','cost_variance_pct','budget_variance_status','budget_variance_reason_code','budget_variance_action_code','currency','budget_revenue_eur','actual_revenue_eur','completeness_pct','missing_categories'],finance.fields.map(row=>[row.fieldId,row.field,row.crop,n(row.budgetCostEur),n(row.recordedCostEur),n(row.costVariance.metadata.varianceCents==null?null:row.costVariance.metadata.varianceCents/100),n(row.costVariance.metadata.variancePercent),row.costVariance.status,row.costVariance.reasonCode,row.costVariance.actionCode,row.costVariance.metadata.currency,n(row.budgetRevenueEur),n(row.recordedRevenueEur),row.completenessPercent,row.completenessResult.reasons.map(reason=>reason.code).join('; ')]));
}
