import { Topbar } from '@/components/layout/Topbar';
import { db } from '@/lib/db';
import { requireFarm } from '@/lib/require-farm';
import { getFinanceData } from '@/lib/finance-data';
import styles from '@/components/operations/Operations.module.css';

export const dynamic='force-dynamic';
export default async function ReportsPage({searchParams}:{searchParams:Promise<{seasonId?:string}>}){const farm=await requireFarm(),params=await searchParams;const seasons=await db.season.findMany({where:{farmId:farm.id},orderBy:{year:'desc'}}),seasonId=params.seasonId??seasons[0]?.id;const finance=seasonId?await getFinanceData(farm,seasonId):null;return <><Topbar title="Economics reports" subtitle="Operational economics, not statutory accounting" farmName={farm.name}/><main className={styles.page}><section className={styles.card}><h2>Report preview</h2><form method="get" className={styles.form}><label>Season<select name="seasonId" defaultValue={seasonId}>{seasons.map(s=><option key={s.id} value={s.id}>{s.year}{s.isActive?' · active':''}</option>)}</select></label><button>Preview season</button></form>{finance&&<p>{finance.fields.length} fields · {finance.fields.reduce((sum,row)=>sum+row.hectares,0).toFixed(2)} ha · {finance.completenessPercent}% complete · {finance.missingData.length?`Missing: ${finance.missingData.join(', ')}`:'No completeness gaps detected'}</p>}</section>{seasonId&&<section className={styles.grid}><ReportGroup title="PDF reports" links={[['Field cost','field_cost'],['Crop comparison','crop_comparison'],['Season gross margin','season_gross_margin'],['Budget vs actual','budget_vs_actual'],['Purchase history','purchase_history'],['Cost-source breakdown','cost_source_breakdown']]} format="pdf" seasonId={seasonId}/><ReportGroup title="CSV exports" links={[['Field economics','field_economics'],['Crop economics','crop_economics'],['Purchases','purchases'],['Expenses','expenses'],['Harvest','harvest'],['Revenue','revenue'],['Budget vs actual','budget_vs_actual'],['Unallocated records','unallocated_records']]} format="csv" seasonId={seasonId}/></section>}<p className={styles.muted}>Report generation requires an internet connection. Exports are farm-scoped, effective records only by default, and each carries an export ID, a content checksum, a generated timestamp and an operational-economics disclaimer.</p></main></>}
function ReportGroup({title,links,format,seasonId}:{title:string;links:string[][];format:string;seasonId:string}){return <section className={styles.card}><h2>{title}</h2><ul className={styles.list}>{links.map(([label,type])=><li key={type}><a className={styles.button} href={`/api/economics/export?seasonId=${seasonId}&format=${format}&type=${type}`}>{label}</a></li>)}</ul><p className={styles.muted}>Effective records only by default. Export ID, timestamp, completeness, and disclaimer are included.</p></section>}
