import type { DashboardData } from '@/types/farm';

// Realistic mock data for a Dutch arable farm in Gelderland.
// Crops: wheat, potato, onion, sugar beet — typical NL mix.
// All prices in EUR; yields in tonnes/ha; areas in hectares.
export const mockDashboardData: DashboardData = {
  farm: {
    id: 'farm-001',
    name: 'Maatschap De Ridder',
    location: 'Westervoort, Gelderland',
    country: 'NL',
    totalHectares: 187,
    brpNumber: '12345678',
    vatNumber: 'NL854321123B01',
  },

  briefing: [
    {
      id: 'b1',
      priority: 'high',
      title: 'Spray window open — close Thursday 18:00',
      explanation:
        'Wind 10 km/h NE, no rain until Friday. T2 fungicide deadline approaching for wheat fields 4, 7, 9.',
      relatedModule: 'activities',
      actionLabel: 'Log spray activity',
    },
    {
      id: 'b2',
      priority: 'high',
      title: 'KAS 27% nitrogen below minimum stock',
      explanation:
        '1.2 T in stock — minimum is 2.0 T. Top-dress applications for sugar beet start next week.',
      relatedModule: 'inventory',
      actionLabel: 'View inventory',
    },
    {
      id: 'b3',
      priority: 'medium',
      title: 'Field "Achterste Kamp" needs scouting',
      explanation:
        'NDVI dropped 11% this week (score 51). Possible early Septoria or moisture stress. Scout before next spray.',
      relatedModule: 'fields',
      actionLabel: 'View field',
    },
    {
      id: 'b4',
      priority: 'medium',
      title: 'Wheat margin: €187/ha — within target',
      explanation:
        'Season costs to date: €1,847/ha. Expected revenue at €185/t: €2,034/ha. Budget variance: −€12,400 (inputs over).',
      relatedModule: 'finance',
      actionLabel: 'View finance',
    },
  ],

  weather: {
    location: 'Westervoort, Gelderland',
    currentTempCelsius: 14,
    currentCondition: 'partly_cloudy',
    days: [
      {
        date: '2025-07-03',
        tempMaxCelsius: 17,
        tempMinCelsius: 11,
        rainMm: 0,
        windSpeedKmh: 10,
        windDirection: 'NE',
        condition: 'partly_cloudy',
        sprayWindow: 'open',
      },
      {
        date: '2025-07-04',
        tempMaxCelsius: 15,
        tempMinCelsius: 10,
        rainMm: 1,
        windSpeedKmh: 14,
        windDirection: 'NE',
        condition: 'cloudy',
        sprayWindow: 'open',
      },
      {
        date: '2025-07-05',
        tempMaxCelsius: 13,
        tempMinCelsius: 9,
        rainMm: 8,
        windSpeedKmh: 22,
        windDirection: 'SW',
        condition: 'rain',
        sprayWindow: 'closed',
      },
      {
        date: '2025-07-06',
        tempMaxCelsius: 12,
        tempMinCelsius: 8,
        rainMm: 14,
        windSpeedKmh: 26,
        windDirection: 'SW',
        condition: 'rain',
        sprayWindow: 'closed',
      },
      {
        date: '2025-07-07',
        tempMaxCelsius: 16,
        tempMinCelsius: 10,
        rainMm: 2,
        windSpeedKmh: 12,
        windDirection: 'W',
        condition: 'partly_cloudy',
        sprayWindow: 'marginal',
      },
    ],
  },

  tasks: [
    {
      id: 't1',
      farmId: 'farm-001',
      fieldId: 'f4',
      title: 'T2 fungicide — Fields 4, 7, 9',
      description: 'Amistar Opti 1.5 L/ha. Verify wind < 15 km/h before starting.',
      type: 'spray',
      priority: 'high',
      status: 'pending',
      dueDate: '2025-07-04',
      assignedTo: 'Jan de Ridder',
      relatedModule: 'activities',
    },
    {
      id: 't2',
      farmId: 'farm-001',
      fieldId: 'f7',
      title: 'Scout Achterste Kamp — NDVI alert',
      description: 'Check for Septoria tritici and moisture stress. Take photos.',
      type: 'scout',
      priority: 'high',
      status: 'pending',
      dueDate: '2025-07-03',
      assignedTo: 'Jan de Ridder',
      relatedModule: 'fields',
    },
    {
      id: 't3',
      farmId: 'farm-001',
      title: 'Order KAS 27% — min 4 tonnes',
      description: 'Current: 1.2 T. Need ≥ 3.5 T for sugar beet top-dress next week.',
      type: 'order',
      priority: 'high',
      status: 'pending',
      dueDate: '2025-07-04',
      relatedModule: 'inventory',
    },
    {
      id: 't4',
      farmId: 'farm-001',
      fieldId: 'f2',
      title: 'Potato haulm killing — Middelste Polder',
      description: 'Reglone 3 L/ha. Schedule for dry weather window.',
      type: 'spray',
      priority: 'medium',
      status: 'pending',
      dueDate: '2025-07-10',
      assignedTo: 'Kees Smit',
      relatedModule: 'activities',
    },
    {
      id: 't5',
      farmId: 'farm-001',
      title: 'Submit July spray diary — RVO',
      description: 'Monthly regulatory submission. Deadline: 15 July.',
      type: 'report',
      priority: 'medium',
      status: 'pending',
      dueDate: '2025-07-15',
      relatedModule: 'compliance',
    },
    {
      id: 't6',
      farmId: 'farm-001',
      fieldId: 'f5',
      title: 'Sugar beet canopy check — Bietenpolder',
      description: 'Cercospora pressure expected after last rain event.',
      type: 'scout',
      priority: 'low',
      status: 'pending',
      dueDate: '2025-07-08',
      assignedTo: 'Kees Smit',
      relatedModule: 'fields',
    },
  ],

  fields: [
    {
      id: 'f1',
      farmId: 'farm-001',
      name: 'Voorste Kamp',
      hectares: 24.3,
      soilType: 'clay',
      currentCrop: 'wheat',
      previousCrop: 'sugar_beet',
      status: 'healthy',
      ndviScore: 78,
    },
    {
      id: 'f2',
      farmId: 'farm-001',
      name: 'Middelste Polder',
      hectares: 31.7,
      soilType: 'clay',
      currentCrop: 'potato',
      previousCrop: 'wheat',
      status: 'healthy',
      ndviScore: 72,
    },
    {
      id: 'f3',
      farmId: 'farm-001',
      name: 'Rijnkamp Noord',
      hectares: 18.5,
      soilType: 'loam',
      currentCrop: 'onion',
      previousCrop: 'barley',
      status: 'healthy',
      ndviScore: 65,
    },
    {
      id: 'f4',
      farmId: 'farm-001',
      name: 'Lange Akker',
      hectares: 28.9,
      soilType: 'clay',
      currentCrop: 'wheat',
      previousCrop: 'potato',
      status: 'healthy',
      ndviScore: 81,
    },
    {
      id: 'f5',
      farmId: 'farm-001',
      name: 'Bietenpolder',
      hectares: 22.1,
      soilType: 'clay',
      currentCrop: 'sugar_beet',
      previousCrop: 'wheat',
      status: 'healthy',
      ndviScore: 69,
    },
    {
      id: 'f6',
      farmId: 'farm-001',
      name: 'Kleine Hoeve',
      hectares: 14.8,
      soilType: 'sandy',
      currentCrop: 'potato',
      previousCrop: 'onion',
      status: 'healthy',
      ndviScore: 74,
    },
    {
      id: 'f7',
      farmId: 'farm-001',
      name: 'Achterste Kamp',
      hectares: 26.4,
      soilType: 'loam',
      currentCrop: 'wheat',
      previousCrop: 'barley',
      status: 'attention',
      ndviScore: 51,
    },
    {
      id: 'f8',
      farmId: 'farm-001',
      name: 'Waalrand',
      hectares: 20.3,
      soilType: 'clay',
      currentCrop: 'sugar_beet',
      previousCrop: 'wheat',
      status: 'healthy',
      ndviScore: 76,
    },
  ],

  // Items below minimum stock or expiring within 30 days
  inventoryAlerts: [
    {
      id: 'inv-1',
      farmId: 'farm-001',
      name: 'KAS 27% Nitrogen',
      category: 'fertilizer',
      unit: 'T',
      currentStock: 1.2,
      minimumStock: 2.0,
      purchasePricePerUnit: 340,
      supplierName: 'Agrifirm',
    },
    {
      id: 'inv-2',
      farmId: 'farm-001',
      name: 'Reglone (diquat 200 g/L)',
      category: 'herbicide',
      activeIngredient: 'Diquat dibromide',
      unit: 'L',
      currentStock: 4.5,
      minimumStock: 10,
      purchasePricePerUnit: 28,
      expiryDate: '2025-09-30',
      supplierName: 'Bayer',
      registrationNumber: 'NL-12234-0001',
    },
    {
      id: 'inv-3',
      farmId: 'farm-001',
      name: 'Amistar Opti (azoxystrobin)',
      category: 'fungicide',
      activeIngredient: 'Azoxystrobin + Chlorothalonil',
      unit: 'L',
      currentStock: 8,
      minimumStock: 5,
      purchasePricePerUnit: 32,
      expiryDate: '2025-08-15',
      supplierName: 'Syngenta',
      registrationNumber: 'NL-12890-0003',
    },
  ],

  finance: {
    seasonId: 'season-2025',
    costPerHectareEur: 1847,
    totalExpensesEur: 345389,
    totalRevenueEur: 127400, // partial — potatoes sold
    estimatedMarginEur: 33319,
    estimatedMarginPerHaEur: 187,
    budgetVarianceEur: -12400, // over budget on inputs
    cropBreakdown: [
      {
        crop: 'wheat',
        hectares: 79.6,
        revenueEur: 0,         // not yet harvested
        costEur: 146943,
        marginEur: 14889,      // estimated
        marginPerHaEur: 187,
      },
      {
        crop: 'potato',
        hectares: 46.5,
        revenueEur: 127400,
        costEur: 102300,
        marginEur: 25100,
        marginPerHaEur: 540,
      },
      {
        crop: 'onion',
        hectares: 18.5,
        revenueEur: 0,
        costEur: 37000,
        marginEur: 9250,       // estimated
        marginPerHaEur: 500,
      },
      {
        crop: 'sugar_beet',
        hectares: 42.4,
        revenueEur: 0,
        costEur: 59146,
        marginEur: 7632,       // estimated
        marginPerHaEur: 180,
      },
    ],
  },

  compliance: [
    {
      id: 'comp-1',
      title: 'July Spray Diary — RVO',
      description: 'Monthly spray record submission required by RVO before 15 July',
      status: 'missing',
      dueDate: '2025-07-15',
      module: 'spray_diary',
    },
    {
      id: 'comp-2',
      title: 'CAP Eco-scheme B',
      description: '3 qualifying activities remaining for full €45/ha eco-scheme bonus',
      status: 'missing',
      dueDate: '2025-10-31',
      module: 'cap',
    },
    {
      id: 'comp-3',
      title: 'GlobalG.A.P. Renewal',
      description: 'Certificate expires 1 August — renewal audit required',
      status: 'expiring',
      dueDate: '2025-08-01',
      module: 'certificate',
    },
    {
      id: 'comp-4',
      title: 'June Spray Diary — RVO',
      description: 'Submitted and confirmed by RVO',
      status: 'complete',
      module: 'spray_diary',
    },
  ],
};
