import 'server-only';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { db } from '@/lib/db';
import type { Farm } from '@prisma/client';
import { escapeCsvValue } from '@/lib/compliance-export/csv';

export async function getScoutingReportData(farm:Farm,fieldId?:string){const visits=await db.scoutingVisit.findMany({where:{farmId:farm.id,...(fieldId?{fieldId}:{})},orderBy:{visitDate:'desc'},include:{field:true,fieldSeason:{include:{season:true,cropStageRecords:{orderBy:{observedAt:'desc'}}}},observations:{include:{photos:{include:{annotationVersions:{where:{isEffective:true}},suggestions:{orderBy:{createdAt:'desc'},take:1}}},followUpWorkOrder:true}}}});return{farm,visits,generatedAt:new Date()}}
export const SCOUTING_CSV_HEADERS=['visit_id','field','crop','visit_date','observer','bbch','observation_id','category','issue','certainty','severity','status','affected_percent','description','photo_count','photo_status','annotation_count','effective_annotation_version','annotation_summary','suggestion_review_status','work_order_id'];
export function buildScoutingCsv(data:Awaited<ReturnType<typeof getScoutingReportData>>,exportId:string){const rows=[['export_id',...SCOUTING_CSV_HEADERS],...data.visits.flatMap(visit=>visit.observations.map(observation=>{const synchronized=observation.photos.filter(photo=>photo.uploadStatus==='finalized'),effective=synchronized.flatMap(photo=>photo.annotationVersions),suggestions=synchronized.flatMap(photo=>photo.suggestions);return[exportId,visit.id,visit.field.name,visit.fieldSeason.crop,visit.visitDate.toISOString(),visit.observerId??'',visit.fieldSeason.cropStageRecords.find(stage=>stage.isEffective)?.stageCode??'',observation.id,observation.category,observation.issueType,observation.certainty,observation.severity,observation.status,String(observation.affectedPercent??''),observation.description,String(synchronized.length),observation.photos.map(photo=>photo.uploadStatus).join('; '),String(effective.reduce((sum,version)=>sum+(Array.isArray(version.annotationsJson)?version.annotationsJson.length:0),0)),effective.map(version=>String(version.version)).join('; '),synchronized.flatMap(photo=>Array.isArray(photo.annotationJson)?photo.annotationJson.map(annotation=>typeof annotation==='object'&&annotation&&'label'in annotation?String(annotation.label):'annotation'):[]).join('; '),suggestions.map(suggestion=>suggestion.status).join('; '),observation.followUpWorkOrderId??'']}))];return '\uFEFF'+rows.map(row=>row.map(escapeCsvValue).join(',')).join('\r\n')+'\r\n# Local-only/failed photos are omitted from evidence counts. Suspected issues remain unconfirmed. No signed URL or storage key is included. Ctgb remains authoritative.\r\n'}
export async function buildScoutingPdf(data:Awaited<ReturnType<typeof getScoutingReportData>>,exportId:string){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page=pdf.addPage([595,842]),y=800;const line=(text:string,size=9,strong=false)=>{if(y<55){page=pdf.addPage([595,842]);y=800}page.drawText(text.replace(/[^\x20-\x7E]/g,'?').slice(0,105),{x:42,y,size,font:strong?bold:font,color:rgb(.08,.12,.1)});y-=size+5};line('FarmOS Scouting Report',18,true);line(`Farm: ${data.farm.name} | Export: ${exportId}`);line(`Generated: ${data.generatedAt.toISOString()}`);line('UNCONFIRMED: symptoms/photo suggestions are not diagnoses and never authorize treatment.',8,true);line('Ctgb remains the legal authority for pesticide use.',8,true);y-=8;for(const visit of data.visits){const stage=visit.fieldSeason.cropStageRecords.find(record=>record.isEffective);line(`${visit.field.name} | ${visit.fieldSeason.crop} | ${visit.visitDate.toISOString()} | BBCH ${stage?.stageCode??'not recorded'}`,11,true);for(const observation of visit.observations){line(`${observation.severity.toUpperCase()} ${observation.category}: ${observation.issueType} [${observation.status}; ${observation.certainty}]`);line(`Evidence: ${observation.description}`);line(`Affected: ${observation.affectedPercent??'not recorded'}% | Synchronized photos: ${observation.photos.filter(photo=>photo.uploadStatus==='finalized').length} | Work order: ${observation.followUpWorkOrderId??'none'}`);for(const photo of observation.photos){if(photo.uploadStatus!=='finalized'){line(`Photo omitted: ${photo.uploadStatus} (not synchronized)`);continue}const version=photo.annotationVersions[0];line(`Photo ${photo.id}: ${photo.mimeType}, ${photo.sizeBytes} bytes, ${Array.isArray(photo.annotationJson)?photo.annotationJson.length:0} annotation(s)`);line(`Annotation version: ${version?.version??'legacy'}${version?.correctionReason?' (corrected)':''} | Suggestion review: ${photo.suggestions[0]?.status??'none'}`)}y-=5}}return pdf.save()}
