export const SCOUTING_SCHEMA_VERSION=1;
export type LocalPhotoState='local_only'|'waiting_to_upload'|'uploading'|'uploaded'|'needs_review'|'failed'|'removed';
export interface LocalScoutingPhoto{localPhotoId:string;localObservationId:string;idempotencyKey:string;file:Blob;name:string;mimeType:string;size:number;capturedAt:string;annotations:Array<{id:string;type:'point'|'rectangle'|'text';x:number;y:number;width?:number;height?:number;label:string}>;status:LocalPhotoState;serverPhotoId?:string;error?:string;retryCount?:number;lastAttemptAt?:string;failureCategory?:string;checkpoint?:'local'|'authorization_created'|'binary_uploaded'|'checksum_verified'|'db_attached'|'finalized';}
export interface LocalScoutingObservation{localObservationId:string;idempotencyKey:string;category:string;issueType:string;severity:string;affectedPercent?:number;description:string;serverObservationId?:string;photos:LocalScoutingPhoto[];}
export interface LocalScoutingDraft{localVisitId:string;localDraftId:string;idempotencyKey:string;namespace:string;farmId:string;userRef:string;fieldSeasonId:string;visitDate:string;stageCode?:string;stageLabel?:string;overallCondition?:string;notes?:string;observations:LocalScoutingObservation[];createdAt:string;updatedAt:string;schemaVersion:number;syncStatus:'draft'|'ready_to_sync'|'syncing'|'partially_synced'|'synced'|'conflict'|'failed';serverVisitId?:string;error?:string;}
const DB='farmos-scouting-offline',VERSION=1,STORE='visits';
function open(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'localVisitId'});s.createIndex('namespace','namespace');}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function done(tx:IDBTransaction){return new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
export async function putScoutingDraft(draft:LocalScoutingDraft){const usage=draft.observations.flatMap(o=>o.photos).reduce((n,p)=>n+p.size,0);if(usage>100*1024*1024)throw new Error('Offline scouting photos exceed the 100 MB local quota.');const db=await open(),tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(draft);await done(tx);db.close();}
export async function listScoutingDrafts(namespace:string){const db=await open(),tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).index('namespace').getAll(namespace);const rows=await new Promise<LocalScoutingDraft[]>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});await done(tx);db.close();return rows.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
export async function getScoutingDraft(localVisitId:string){const db=await open(),tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(localVisitId);const row=await new Promise<LocalScoutingDraft|undefined>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});await done(tx);db.close();return row;}
export async function updateScoutingPhotoAnnotations(input:{localVisitId:string;localPhotoId:string;namespace:string;annotations:LocalScoutingPhoto['annotations']}){const draft=await getScoutingDraft(input.localVisitId);if(!draft||draft.namespace!==input.namespace)throw new Error('The active farm/user session does not own this local photo.');let found=false;for(const observation of draft.observations)for(const photo of observation.photos)if(photo.localPhotoId===input.localPhotoId){if(photo.status==='uploaded')throw new Error('Synchronized evidence must be corrected from its private photo page.');photo.annotations=input.annotations;photo.checkpoint='local';photo.error=undefined;found=true}if(!found)throw new Error('Local photo was not found.');draft.updatedAt=new Date().toISOString();draft.syncStatus=draft.serverVisitId?'partially_synced':'ready_to_sync';await putScoutingDraft(draft);return draft;}
export async function deleteScoutingDraft(localVisitId:string){const db=await open(),tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(localVisitId);await done(tx);db.close();}
export function scoutingRecoveryManifest(drafts:LocalScoutingDraft[]){return{format:'farmos-scouting-recovery',schemaVersion:1,exportedAt:new Date().toISOString(),photosIncluded:false,warning:'Photo binaries are excluded from JSON. Keep this device until uploads finish; JSON is not a complete photo backup.',visits:drafts.map(d=>({...d,observations:d.observations.map(o=>({...o,photos:o.photos.map(p=>({...p,file:undefined,binaryExcluded:true}))}))}))};}
