'use client';
import { useRef, useState } from 'react';
import { createPoint, createRectangle, createText, editLabel, moveAnnotation, removeAnnotation, resizeRectangle, undo, type EditorState } from '@/lib/scouting/annotation-editor';
import type { PhotoAnnotation } from '@/lib/scouting/photo-policy';
import styles from './PhotoAnnotationEditor.module.css';

type Props={src:string;annotations:PhotoAnnotation[];onSave:(annotations:PhotoAnnotation[])=>void|Promise<void>;onCancel:()=>void;saving?:boolean};
export function PhotoAnnotationEditor({src,annotations,onSave,onCancel,saving=false}:Props){
 const[state,setState]=useState<EditorState>({annotations,history:[]}),[tool,setTool]=useState<'point'|'rectangle'|'text'|'move'>('point'),[selected,setSelected]=useState<string|null>(null),drag=useRef<{x:number;y:number;id?:string}|null>(null),box=useRef<HTMLDivElement>(null);
 const point=(event:React.PointerEvent)=>{const rect=box.current!.getBoundingClientRect(),unit=(value:number)=>Number.isFinite(value)?Math.max(0,Math.min(1,value)):.5;return{x:unit((event.clientX-rect.left)/rect.width),y:unit((event.clientY-rect.top)/rect.height)}};
 function down(event:React.PointerEvent){try{event.currentTarget.setPointerCapture(event.pointerId)}catch{/* Pointer capture is optional for synthetic/WebKit sources. */}const position=point(event);drag.current={...position,id:selected??undefined};if(tool==='point'){const label=prompt('Point label (optional)')??'';setState(state=>createPoint(state,position.x,position.y,label))}if(tool==='text'){const label=prompt('Text label')??'';if(label)setState(state=>createText(state,position.x,position.y,label))}}
 function up(event:React.PointerEvent){if(!drag.current)return;const position=point(event),start=drag.current;if(tool==='rectangle')setState(state=>createRectangle(state,start.x,start.y,position.x,position.y,'Area'));else if(tool==='move'&&start.id)setState(state=>moveAnnotation(state,start.id,position.x-start.x,position.y-start.y));drag.current=null}
 return <div className={styles.editor}><div className={styles.toolbar} role="toolbar" aria-label="Annotation tools">{(['point','rectangle','text','move']as const).map(value=><button type="button" aria-pressed={tool===value} key={value} onClick={()=>setTool(value)}>{value}</button>)}<button type="button" onClick={()=>setState(undo)}>Undo</button></div><div ref={box} className={styles.canvas} onPointerDown={down} onPointerUp={up}><img src={src} alt="Photo being annotated" draggable={false}/>{state.annotations.map(annotation=><button type="button" key={annotation.id} aria-label={`${annotation.type}: ${annotation.label||'unlabelled'}`} onClick={event=>{event.stopPropagation();setSelected(annotation.id)}} className={`${styles.mark} ${annotation.type==='rectangle'?styles.rectangle:styles.point} ${selected===annotation.id?styles.selected:''}`} style={{left:`${annotation.x*100}%`,top:`${annotation.y*100}%`,width:annotation.type==='rectangle'?`${(annotation.width??.04)*100}%`:undefined,height:annotation.type==='rectangle'?`${(annotation.height??.04)*100}%`:undefined}}>{annotation.type==='rectangle'?'':annotation.label||'•'}</button>)}</div><ul className={styles.list}>{state.annotations.map(annotation=><li key={annotation.id}><button type="button" onClick={()=>setSelected(annotation.id)}>{annotation.type}: {annotation.label||'unlabelled'}</button><button type="button" onClick={()=>{const label=prompt('Edit label',annotation.label);if(label!=null)setState(state=>editLabel(state,annotation.id,label))}}>Edit label</button>{annotation.type==='rectangle'&&<button type="button" onClick={()=>setState(state=>resizeRectangle(state,annotation.id,(annotation.width??.1)+.05,(annotation.height??.1)+.05))}>Resize +</button>}<button type="button" onClick={()=>setState(state=>removeAnnotation(state,annotation.id))}>Delete</button></li>)}</ul><div className={styles.actions}><button type="button" onClick={onCancel} disabled={saving}>Cancel changes</button><button type="button" onClick={()=>onSave(state.annotations)} disabled={saving}>{saving?'Saving…':'Save annotations'}</button></div></div>
}
